apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-registry
  name: mysql-service
  namespace: project-02-k8s-app
spec:
  clusterIP: None
  ports:
  - port: 3306
  selector:
    app: db-registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db-registry
  name: db-registry
  namespace: project-02-k8s-app
spec:
  serviceName: "mysql-service"
  replicas: 2
  selector:
    matchLabels:
      app: db-registry
  template:
    metadata:
      labels:
        app: db-registry
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: db-secret
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_ROOT_PASSWORD
              name: db-secret
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: DATABASE_USER
              name: db-config
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: db-config
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - name: mysql-db-data
          mountPath: /var/lib/mysql
        - name: init-script-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script-volume
          configMap:
            name: db-init-script
  volumeClaimTemplates:
  - metadata:
      name: mysql-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-share
      resources:
        requests:
          storage: 10Mi
status: {}
