apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `lab-db`;
    USE `lab-db`;
    CREATE TABLE IF NOT EXISTS lab_table (
        id INT AUTO_INCREMENT PRIMARY KEY,
        worker_node VARCHAR(100) NOT NULL,
        status_metric VARCHAR(50) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
