apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: project-02-k8s-app
spec:
  podSelector: {}
  policyTypes:
  - Ingress


---
# Allow trafic from ingress to application 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-registry
  namespace: project-02-k8s-app
spec:
  podSelector:
    matchLabels:
      role: web
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-nginx
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
---
# Allow for web to db of readiness probe
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-to-mysql
  namespace: project-02-k8s-app
spec:
  podSelector:
    matchLabels:
      role: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: project-02-k8s-app
      podSelector:
        matchLabels:
          role: web
    ports:
    - protocol: TCP
      port: 3306
