expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "harbor-tls"
  ingress:
    hosts:
      core: harbor.fcvlab.com
    className: "nginx"
externalURL: https://harbor.fcvlab.com
harborAdminPassword: "admin"
